
version: '3.9'

networks:
  dev_network:


services:

  db:
    build: db
    ports:
      - "5432:5432"
    networks:
      dev_network:
        aliases:
          - db-main

  app:
    build:
      context: .
      args:
        PG_DSN: 'postgresql://admin:1234@db-main/flask_netology'
    ports:
      - "5000:5000"
    networks:
      dev_network:
        aliases:
          - app
    volumes:
      - ./:/app